/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    500: typeof import('./src/components/500.vue')['default']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    BaseDottitText: typeof import('./src/components/layout/BaseDottitText.vue')['default']
    BaseDraggle: typeof import('./src/components/layout/BaseDraggle.vue')['default']
    BaseEcharts: typeof import('./src/components/layout/BaseEcharts.vue')['default']
    BaseFormer: typeof import('./src/components/layout/BaseFormer.vue')['default']
    BaseLoading: typeof import('./src/components/layout/BaseLoading.vue')['default']
    BaseNumberStep: typeof import('./src/components/layout/BaseNumberStep.vue')['default']
    BaseTable: typeof import('./src/components/layout/BaseTable.vue')['default']
    Chat: typeof import('./src/components/chat/index.vue')['default']
    ChatBox: typeof import('./src/components/chat/chatBox.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Language: typeof import('./src/components/layout/language.vue')['default']
    Login: typeof import('./src/components/userProfile/Login.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer.vue')['default']
    Redirect: typeof import('./src/components/userProfile/redirect.vue')['default']
    Register: typeof import('./src/components/userProfile/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectReq: typeof import('./src/components/userProfile/SelectReq.vue')['default']
    SvgIcon: typeof import('./src/components/layout/svg-icon.vue')['default']
    VerifyCode: typeof import('./src/components/common/verifyCode.vue')['default']
  }
}
